#ifndef TAG_TYPES_H_
#define TAG_TYPES_H_

#define DIETAG 1
#define SLICE_TAG 2
#define SLICE_SIZE_TAG 3
#define SLICE_TYPE_TAG 4
#define DEMAND_DATA_FROM_UPPER_SLICE_TAG 5
#define DEMAND_DATA_FROM_LOWER_SLICE_TAG 6
#define POINT_DATA_TAG 7
#define DEBUG_MESSAGE_1_TAG 8
#define DEBUG_MESSAGE_2_TAG 9
#define DEBUG_MESSAGE_3_TAG 10
#define DEBUG_MESSAGE_4_TAG 11
#define DEBUG_MESSAGE_FOLLOWUP_TAG 12
#define JOB_DONE_TAG 13

#endif
